### ISSUE TITLE
Flushing cache fail with Magento 2.4.6-beta1

### ISSUE THREAD

**Issue by hostep** [netz98/n98-magerun2#1083]
## Describe the bug

Using:
- Magento OS 2.4.6-beta1
- Magerun2 6.1.1
- PHP 8.17.0

## Expected behaviour

Being able to flush Magento's cache using magerun2

## Steps to reproduce the issue

1. Execute:
```
./n98-magerun2.phar cache:flush
```

2. See error:
```
PHP Fatal error:  Uncaught TypeError: Return value of "N98\Magento\Command\Cache\FlushCommand::execute()" must be of the type int, "null" returned. in vendor/symfony/console/Command/Command.php:301
Stack trace:
#0 phar://n98-magerun2.phar/src/N98/Magento/Command/AbstractMagentoCommand.php(249): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 phar://n98-magerun2.phar/vendor/symfony/console/Application.php(1039): N98\Magento\Command\AbstractMagentoCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 phar://n98-magerun2.phar/vendor/symfony/console/Application.php(275): Symfony\Component\Console\Application->doRunCommand(Object(N98\Magento\Command\Cache\FlushCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 phar://n98-magerun2.phar/src/N98/Magento/Application.php(235): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 phar://n98-magerun2.phar/vendor/symfony/console/Application.php(149): N98\Magento\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 phar://n98-magerun2.phar/src/N98/Magento/Application.php(338): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 n98-magerun2.phar(8): N98\Magento\Application->run()
#7 {main}
  thrown in vendor/symfony/console/Command/Command.php on line 301
```

Maybe other commands have the same problem? <del>I haven't tested any other yet.</del>
_Update:_ Just for fun I tried `./n98-magerun2.phar setup:di:compile` and that one also crashes about halfway through:

```
PHP Fatal error:  During inheritance of Countable: Uncaught Exception: Deprecated Functionality: Return type of Laminas\Filter\FilterChain::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar://n98-magerun2.phar/vendor/laminas/laminas-filter/src/FilterChain.php on line 92 in vendor/magento/framework/App/ErrorHandler.php:62
Stack trace:
#0 phar://n98-magerun2.phar/vendor/laminas/laminas-filter/src/FilterChain.php(10): Magento\Framework\App\ErrorHandler->handler(8192, 'Return type of ...', 'phar://...', 92)
#1 phar://n98-magerun2.phar/vendor/composer/ClassLoader.php(578): include('phar://...')
#2 phar://n98-magerun2.phar/vendor/composer/ClassLoader.php(432): Composer\Autoload\ClassLoader::Composer\Autoload\{closure}('phar://...')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('Laminas\\Filter\\...')
#4 vendor/magento/framework/GetParameterClassTrait.php(34): ReflectionClass->__construct('Laminas\\Filter\\...')
#5 vendor/magento/framework/Code/Reader/ClassReader.php(42): Magento\Framework\Code\Reader\ClassReader->getParameterClass(Object(ReflectionParameter))
#6 setup/src/Magento/Setup/Module/Di/Code/Reader/ClassReaderDecorator.php(35): Magento\Framework\Code\Reader\ClassReader->getConstructor('Magento\\Framewo...')
#7 setup/src/Magento/Setup/Module/Di/Code/Reader/Decorator/Area.php(53): Magento\Setup\Module\Di\Code\Reader\ClassReaderDecorator->getConstructor('Magento\\Framewo...')
#8 setup/src/Magento/Setup/Module/Di/App/Task/Operation/Area.php(116): Magento\Setup\Module\Di\Code\Reader\Decorator\Area->getList('...')
#9 setup/src/Magento/Setup/Module/Di/App/Task/Operation/Area.php(87): Magento\Setup\Module\Di\App\Task\Operation\Area->getDefinitionsCollection('...')
#10 setup/src/Magento/Setup/Module/Di/App/Task/Manager.php(56): Magento\Setup\Module\Di\App\Task\Operation\Area->doOperation()
#11 setup/src/Magento/Setup/Console/Command/DiCompileCommand.php(216): Magento\Setup\Module\Di\App\Task\Manager->process(Object(Closure), Object(Closure))
#12 vendor/symfony/console/Command/Command.php(298): Magento\Setup\Console\Command\DiCompileCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 phar://n98-magerun2.phar/vendor/symfony/console/Application.php(1039): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 phar://n98-magerun2.phar/vendor/symfony/console/Application.php(275): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Setup\Console\Command\DiCompileCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 phar://n98-magerun2.phar/src/N98/Magento/Application.php(235): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 phar://n98-magerun2.phar/vendor/symfony/console/Application.php(149): N98\Magento\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 phar://n98-magerun2.phar/src/N98/Magento/Application.php(338): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 n98-magerun2.phar(8): N98\Magento\Application->run()
#19 {main} in phar://n98-magerun2.phar/vendor/laminas/laminas-filter/src/FilterChain.php on line 10
```

## Technical details

The package `symfony/console` is being upgraded from version 4.4.x to 5.4.x when going from Magento 2.4.5-p1 to 2.4.6-beta1
Maybe that's one of the problems?

**Comment by cmuench** [comment]
@hostep Sounds like a lot of backwards compatibility issues.

**Comment by cmuench** [comment]
@hostep Just did a test run with our phar test suite. All commands are working but I see a lot of "Uncaught TypeError: Return value" errors. So there is hope that we can fix them. Functionality seems not to be broken.

**Comment by cmuench** [comment]
@hostep Update is a bit bigger. We have to update the Symfony dependencies from 4.4 to 5.4.

**Comment by cmuench** [comment]
@hostep I have a good and a bad news.

Good news: I have Magento 2.4.6 running in a branch.
Bad news: All older Magento versions are broken after the Symfony update in n98-magerun2.

I am just looking for a good solution.

**Comment by hostep** [comment]
Maybe it's time for a major version 7 which drops support for Magento 2.4.5 and lower? Or would you rather avoid this?

**Comment by cmuench** [comment]
That's what I try to prevent.

**Comment by cmuench** [comment]
@hostep I have implemented a experimental `MagentoCoreProxyCommand` which will execute all core commands by running bin/magento in the background. That prevents that we load two kind of symfony/console components.
Additionally we prevent to bootstrap Magento twice which is IMHO the issue for some open issues related to DB locks.
Let's see how that can work.

**Comment by cmuench** [comment]
@hostep Did some work and tests with the new proxy command logic.
If you want to test, there is a generated phar in the PR.
See here: https://github.com/netz98/n98-magerun2/pull/1085#issuecomment-1385125684

**Comment by hostep** [comment]
Awesome work @cmuench

Haven't had the chance yet to test, but I trust you've figured it out! 🙂
