### ISSUE TITLE
Getting Error Uncaught TypeError: Magento\ApplicationPerformanceMonitor\Plugin\ApplicationPerformanceMonitor::aroundLaunch(): Return value must be of type Magento\Framework\App\ResponseInterface, null returned

### ISSUE THREAD

**Issue by thecodecook14** [netz98/n98-magerun2#1389]
## Describe the bug

With Magento's latest development branch 2.4-develop, I am always getting the below error with this command `n98-magerun2 sys:cron:run indexer_update_all_views`:

```
PHP Fatal error:  Uncaught TypeError: Magento\ApplicationPerformanceMonitor\Plugin\ApplicationPerformanceMonitor::aroundLaunch(): Return value must be of type Magento\Framework\App\ResponseInterface, null returned in app/code/Magento/ApplicationPerformanceMonitor/Plugin/ApplicationPerformanceMonitor.php:38
Stack trace:
#0 lib/internal/Magento/Framework/Interception/Interceptor.php(135): Magento\ApplicationPerformanceMonitor\Plugin\ApplicationPerformanceMonitor->aroundLaunch(Object(N98\Magento\Framework\App\Magerun\Interceptor), Object(Closure))
#1 lib/internal/Magento/Framework/Interception/Interceptor.php(153): N98\Magento\Framework\App\Magerun\Interceptor->Magento\Framework\Interception\{closure}()
#2 generated/code/N98/Magento/Framework/App/Magerun/Interceptor.php(23): N98\Magento\Framework\App\Magerun\Interceptor->___callPlugins('launch', Array, NULL)
#3 phar:///opt/homebrew/bin/n98-magerun2/src/N98/Magento/Application/Magento2Initializer.php(63): N98\Magento\Framework\App\Magerun\Interceptor->launch()
#4 phar:///opt/homebrew/bin/n98-magerun2/src/N98/Magento/Application.php(278): N98\Magento\Application\Magento2Initializer->init('/opt/homebrew/v...')
#5 phar:///opt/homebrew/bin/n98-magerun2/src/N98/Magento/Application/Console/EventSubscriber/CheckCompatibility.php(78): N98\Magento\Application->initMagento(true)
#6 phar:///opt/homebrew/bin/n98-magerun2/vendor/symfony/event-dispatcher/EventDispatcher.php(230): N98\Magento\Application\Console\EventSubscriber\CheckCompatibility->checkCompatibility(Object(Symfony\Component\Console\Event\ConsoleEvent), 'n98-magerun.app...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#7 phar:///opt/homebrew/bin/n98-magerun2/vendor/symfony/event-dispatcher/EventDispatcher.php(59): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'n98-magerun.app...', Object(Symfony\Component\Console\Event\ConsoleEvent))
#8 phar:///opt/homebrew/bin/n98-magerun2/src/N98/Magento/Application.php(252): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(Symfony\Component\Console\Event\ConsoleEvent), 'n98-magerun.app...')
#9 phar:///opt/homebrew/bin/n98-magerun2/vendor/symfony/console/Application.php(171): N98\Magento\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///opt/homebrew/bin/n98-magerun2/src/N98/Magento/Application.php(363): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /opt/homebrew/bin/n98-magerun2(8): N98\Magento\Application->run()
#12 {main}
  thrown in app/code/Magento/ApplicationPerformanceMonitor/Plugin/ApplicationPerformanceMonitor.php on line 38

Fatal error: Uncaught TypeError: Magento\ApplicationPerformanceMonitor\Plugin\ApplicationPerformanceMonitor::aroundLaunch(): Return value must be of type Magento\Framework\App\ResponseInterface, null returned in app/code/Magento/ApplicationPerformanceMonitor/Plugin/ApplicationPerformanceMonitor.php:38
Stack trace:
#0 lib/internal/Magento/Framework/Interception/Interceptor.php(135): Magento\ApplicationPerformanceMonitor\Plugin\ApplicationPerformanceMonitor->aroundLaunch(Object(N98\Magento\Framework\App\Magerun\Interceptor), Object(Closure))
#1 lib/internal/Magento/Framework/Interception/Interceptor.php(153): N98\Magento\Framework\App\Magerun\Interceptor->Magento\Framework\Interception\{closure}()
#2 generated/code/N98/Magento/Framework/App/Magerun/Interceptor.php(23): N98\Magento\Framework\App\Magerun\Interceptor->___callPlugins('launch', Array, NULL)
#3 phar:///opt/homebrew/bin/n98-magerun2/src/N98/Magento/Application/Magento2Initializer.php(63): N98\Magento\Framework\App\Magerun\Interceptor->launch()
#4 phar:///opt/homebrew/bin/n98-magerun2/src/N98/Magento/Application.php(278): N98\Magento\Application\Magento2Initializer->init('/opt/homebrew/v...')
#5 phar:///opt/homebrew/bin/n98-magerun2/src/N98/Magento/Application/Console/EventSubscriber/CheckCompatibility.php(78): N98\Magento\Application->initMagento(true)
#6 phar:///opt/homebrew/bin/n98-magerun2/vendor/symfony/event-dispatcher/EventDispatcher.php(230): N98\Magento\Application\Console\EventSubscriber\CheckCompatibility->checkCompatibility(Object(Symfony\Component\Console\Event\ConsoleEvent), 'n98-magerun.app...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#7 phar:///opt/homebrew/bin/n98-magerun2/vendor/symfony/event-dispatcher/EventDispatcher.php(59): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'n98-magerun.app...', Object(Symfony\Component\Console\Event\ConsoleEvent))
#8 phar:///opt/homebrew/bin/n98-magerun2/src/N98/Magento/Application.php(252): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(Symfony\Component\Console\Event\ConsoleEvent), 'n98-magerun.app...')
#9 phar:///opt/homebrew/bin/n98-magerun2/vendor/symfony/console/Application.php(171): N98\Magento\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///opt/homebrew/bin/n98-magerun2/src/N98/Magento/Application.php(363): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /opt/homebrew/bin/n98-magerun2(8): N98\Magento\Application->run()
#12 {main}
  thrown in app/code/Magento/ApplicationPerformanceMonitor/Plugin/ApplicationPerformanceMonitor.php on line 38
```

## Expected behaviour

It Should run the `indexer_update_all_views` indexer
## Steps to reproduce the issue
Run the below command in order to reproduce the issue:

`n98-magerun2 sys:cron:run indexer_update_all_views`

## Technical details

My Enviournment is as follows:

- OS: Mac
- Magento - 2.4-develop branch
- PHP 8.2.9
- composer 2.6.4

**Comment by cmuench** [comment]
@thecodecook14 thanks for reporting. I created a patch and already deployed it to the develop version.
You can test by upgrading the phar with `n98-magerun2.phar self-update --unstable`.
