### ISSUE TITLE
Fatal Error in Magento 2 after Phive installation

### ISSUE THREAD

**Issue by cmuench** [netz98/n98-magerun2#342]
It got this error:

`PHP Fatal error:  Uncaught Error: Class 'Symfony\Polyfill\Php72\Php72' not found`

This seems to be related to the Phive installation with Symlinks.

Complete stacktrace:

<pre><code>
Fatal error: Uncaught Error: Class 'Symfony\Polyfill\Php72\Php72' not found in /Users/cmuench/Workspaces/PHP/n98/customers/my-shop/vendor/symfony/polyfill-php72/bootstrap.php:29
Stack trace:
#0 /Users/cmuench/Workspaces/PHP/n98/customers/my-shop/vendor/composer/autoload_real.php(71): require()
#1 /Users/cmuench/Workspaces/PHP/n98/customers/my-shop/vendor/composer/autoload_real.php(61): composerRequire30337b268d6b98ebf07f17f4df6df248('25072dd6e247008...', '/Users/cmuench/...')
#2 /Users/cmuench/Workspaces/PHP/n98/customers/my-shop/vendor/autoload.php(7): ComposerAutoloaderInit30337b268d6b98ebf07f17f4df6df248::getLoader()
#3 /Users/cmuench/Workspaces/PHP/n98/customers/my-shop/app/autoload.php(30): include('/Users/cmuench/...')
#4 /Users/cmuench/Workspaces/PHP/n98/customers/my-shop/app/bootstrap.php(30): require_once('/Users/cmuench/...')
#5 phar:///Users/cmuench/.phive/phars/n98-magerun2-2.0.0. in /Users/cmuench/Workspaces/PHP/n98/customers/my-shop/vendor/symfony/polyfill-php72/bootstrap.php on line 29
</code></pre>

**Comment by cmuench** [comment]
Problem Silvester with an update of dependencies since v2.1.2.
