### ISSUE TITLE
Fatal error due to Composer autoload generation error

### ISSUE THREAD

**Issue by erikhansen** [netz98/n98-magerun2#348]
Steps to reproduce:

1. Install composer 1.6.1
2. Install Magento 2.2.2 using composer
3. Run `n98-magerun`

Expected results:
1. Magerun will run like normal

Actual results:
1. An error like this will be generated:
```
PHP Fatal error:  Uncaught Error: Class 'Magento\Framework\Component\ComponentRegistrar' not found in /var/www/sites/example.dev/vendor/magento/framework/registration.php:7
Stack trace:
#0 /var/www/sites/example.dev/vendor/composer/autoload_real.php(71): require()
#1 /var/www/sites/example.dev/vendor/composer/autoload_real.php(61): composerRequiref6f50029db5d39078ddb08e892649761('07ec02c7e667fdc...', '/var/www/sites/...')
#2 /var/www/sites/example.dev/vendor/autoload.php(7): ComposerAutoloaderInitf6f50029db5d39078ddb08e892649761::getLoader()
#3 /var/www/sites/example.dev/app/autoload.php(30): include('/var/www/sites/...')
#4 /var/www/sites/example.dev/app/bootstrap.php(30): require_once('/var/www/sites/...')
#5 phar:///usr/local/bin/mr/src/N98/Magento/Application.php(729): require_once('/var/www/sites/...')
#6 phar:///usr/local/bin/mr/src/N98/Magento/Application.php(735): N98\Magento\Application->N98\Magento\{closure}('/var/www/sites/...')
#7 phar:///usr/local/bin/mr/src/N98/Magento/Application.ph in /var/www/sites/example.dev/vendor/magento/framework/registration.php on line 7
```

Another issue we saw with the autoloader:

```
PHP Warning:  Class 'Zend\Form\FormElementManager\FormElementManagerV2Polyfill' not found in /var/www/sites/example.dev/vendor/zendframework/zend-form/autoload/formElementManagerPolyfill.php on line 16
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/mr:0
PHP   2. N98\Magento\Application->run() /usr/local/bin/mr:8
PHP   3. N98\Magento\Application->init() phar:///usr/local/bin/mr/src/N98/Magento/Application.php:564
PHP   4. N98\Magento\Application->registerMagentoCoreCommands() phar:///usr/local/bin/mr/src/N98/Magento/Application.php:635
PHP   5. N98\Magento\Application->requireOnce() phar:///usr/local/bin/mr/src/N98/Magento/Application.php:266
PHP   6. N98\Magento\Application->N98\Magento\{closure}() phar:///usr/local/bin/mr/src/N98/Magento/Application.php:735
PHP   7. require_once() phar:///usr/local/bin/mr/src/N98/Magento/Application.php:729
PHP   8. require_once() /var/www/sites/example.dev/app/bootstrap.php:30
PHP   9. include() /var/www/sites/example.dev/app/autoload.php:30
PHP  10. ComposerAutoloaderInit5b1e53c594497157f378fd88f3f0d892::getLoader() /var/www/sites/example.dev/vendor/autoload.php:7
PHP  11. composerRequire5b1e53c594497157f378fd88f3f0d892() /var/www/sites/example.dev/vendor/composer/autoload_real.php:61
PHP  12. require() /var/www/sites/example.dev/vendor/composer/autoload_real.php:71
PHP  13. {closure:/var/www/sites/example.dev/vendor/zendframework/zend-form/autoload/formElementManagerPolyfill.php:11-17}() /var/www/sites/example.dev/vendor/zendframework/zend-form/autoload/formElementManagerPolyfill.php:17
PHP  14. class_alias() /var/www/sites/example.dev/vendor/zendframework/zend-form/autoload/formElementManagerPolyfill.php:16
```

**Comment by erikhansen** [comment]
Several of our developers ran into this issue on Magento 2.2.2. Here is the solution we found:

1. Update to the latest version of Composer (1.6.2):
    ```
    composer self-update
    ```
    If the above command doesn't work, try this:
    ```
    sudo /usr/local/bin/composer self-update
    ```
    
2. Run `composer install` to regenerate the autoload file.

This seems to fix the issue.
