### ISSUE TITLE
[v3.0.0] sample:deploy PRE_COMMAND_RUN issue on Magento 2.2.6

### ISSUE THREAD

**Issue by JDavidVR** [netz98/n98-magerun2#413]
Hi today I've upgrade magerun to 3.0.0

n98-magerun2 --version
n98-magerun2 version 3.0.0 by netz98 GmbH

I detected an issue when trying to install sample data using magerun, here is the error:

```
mr2 sample:deploy -vvv
Load dist config
Search for Magento in folder pub
Search for Magento in folder /path/to/m226ee
Found Magento  v2  in folder /path/to/m226ee
Load dist config
Add core command  help -> Symfony\Component\Console\Command\HelpCommand
Add core command  list -> Symfony\Component\Console\Command\ListCommand
Add core command  admin:user:create -> Magento\Setup\Console\Command\AdminUserCreateCommand
Add core command  setup:backup -> Magento\Setup\Console\Command\BackupCommand
Add core command  setup:config:set -> Magento\Setup\Console\Command\ConfigSetCommand
Add core command  setup:cron:run -> Magento\Setup\Console\Command\CronRunCommand
Add core command  setup:db-data:upgrade -> Magento\Setup\Console\Command\DbDataUpgradeCommand
Add core command  setup:db-schema:upgrade -> Magento\Setup\Console\Command\DbSchemaUpgradeCommand
Add core command  setup:db:status -> Magento\Setup\Console\Command\DbStatusCommand
Add core command  info:dependencies:show-framework -> Magento\Setup\Console\Command\DependenciesShowFrameworkCommand
Add core command  info:dependencies:show-modules-circular -> Magento\Setup\Console\Command\DependenciesShowModulesCircularCommand
Add core command  info:dependencies:show-modules -> Magento\Setup\Console\Command\DependenciesShowModulesCommand
Add core command  setup:di:compile -> Magento\Setup\Console\Command\DiCompileCommand
Add core command  setup:performance:generate-fixtures -> Magento\Setup\Console\Command\GenerateFixturesCommand
Add core command  i18n:collect-phrases -> Magento\Setup\Console\Command\I18nCollectPhrasesCommand
Add core command  i18n:pack -> Magento\Setup\Console\Command\I18nPackCommand
Add core command  info:adminuri -> Magento\Setup\Console\Command\InfoAdminUriCommand
Add core command  info:backups:list -> Magento\Setup\Console\Command\InfoBackupsListCommand
Add core command  info:currency:list -> Magento\Setup\Console\Command\InfoCurrencyListCommand
Add core command  info:language:list -> Magento\Setup\Console\Command\InfoLanguageListCommand
Add core command  info:timezone:list -> Magento\Setup\Console\Command\InfoTimezoneListCommand
Add core command  setup:install -> Magento\Setup\Console\Command\InstallCommand
Add core command  setup:store-config:set -> Magento\Setup\Console\Command\InstallStoreConfigurationCommand
Add core command  module:enable -> Magento\Setup\Console\Command\ModuleEnableCommand
Add core command  module:disable -> Magento\Setup\Console\Command\ModuleDisableCommand
Add core command  module:status -> Magento\Setup\Console\Command\ModuleStatusCommand
Add core command  module:uninstall -> Magento\Setup\Console\Command\ModuleUninstallCommand
Add core command  maintenance:allow-ips -> Magento\Setup\Console\Command\MaintenanceAllowIpsCommand
Add core command  maintenance:disable -> Magento\Setup\Console\Command\MaintenanceDisableCommand
Add core command  maintenance:enable -> Magento\Setup\Console\Command\MaintenanceEnableCommand
Add core command  maintenance:status -> Magento\Setup\Console\Command\MaintenanceStatusCommand
Add core command  setup:rollback -> Magento\Setup\Console\Command\RollbackCommand
Add core command  setup:upgrade -> Magento\Setup\Console\Command\UpgradeCommand
Add core command  setup:uninstall -> Magento\Setup\Console\Command\UninstallCommand
Add core command  setup:static-content:deploy -> Magento\Setup\Console\Command\DeployStaticContentCommand
Add core command  store:list -> Magento\Store\Console\Command\StoreListCommand
Add core command  store:website:list -> Magento\Store\Console\Command\WebsiteListCommand
Add core command  theme:uninstall -> Magento\Theme\Console\Command\ThemeUninstallCommand
Add core command  customer:hash:upgrade -> Magento\Customer\Console\Command\UpgradeHashAlgorithmCommand
Add core command  cache:enable -> Magento\Backend\Console\Command\CacheEnableCommand
Add core command  cache:disable -> Magento\Backend\Console\Command\CacheDisableCommand
Add core command  cache:flush -> Magento\Backend\Console\Command\CacheFlushCommand
Add core command  cache:clean -> Magento\Backend\Console\Command\CacheCleanCommand
Add core command  cache:status -> Magento\Backend\Console\Command\CacheStatusCommand
Add core command  indexer:info -> Magento\Indexer\Console\Command\IndexerInfoCommand
Add core command  indexer:reindex -> Magento\Indexer\Console\Command\IndexerReindexCommand
Add core command  indexer:set-mode -> Magento\Indexer\Console\Command\IndexerSetModeCommand
Add core command  indexer:show-mode -> Magento\Indexer\Console\Command\IndexerShowModeCommand
Add core command  indexer:status -> Magento\Indexer\Console\Command\IndexerStatusCommand
Add core command  indexer:reset -> Magento\Indexer\Console\Command\IndexerResetStateCommand
Add core command  indexer:set-dimensions-mode -> Magento\Indexer\Console\Command\IndexerSetDimensionsModeCommand
Add core command  indexer:show-dimensions-mode -> Magento\Indexer\Console\Command\IndexerShowDimensionsModeCommand
Add core command  catalog:images:resize -> Magento\Catalog\Console\Command\ImagesResizeCommand
Add core command  catalog:product:attributes:cleanup -> Magento\Catalog\Console\Command\ProductAttributesCleanUp
Add core command  config:set -> Magento\Config\Console\Command\ConfigSetCommand
Add core command  config:show -> Magento\Config\Console\Command\ConfigShowCommand
Add core command  admin:user:unlock -> Magento\User\Console\UnlockAdminAccountCommand
Add core command  cron:run -> Magento\Cron\Console\Command\CronCommand
Add core command  cron:install -> Magento\Cron\Console\Command\CronInstallCommand
Add core command  cron:remove -> Magento\Cron\Console\Command\CronRemoveCommand
Add core command  deploy:mode:set -> Magento\Deploy\Console\Command\SetModeCommand
Add core command  deploy:mode:show -> Magento\Deploy\Console\Command\ShowModeCommand
Add core command  app:config:dump -> Magento\Deploy\Console\Command\App\ApplicationDumpCommand
Add core command  config:sensitive:set -> Magento\Deploy\Console\Command\App\SensitiveConfigSetCommand
Add core command  app:config:import -> Magento\Deploy\Console\Command\App\ConfigImportCommand
Add core command  app:config:status -> Magento\Deploy\Console\Command\App\ConfigStatusCommand
Add core command  dev:tests:run -> Magento\Developer\Console\Command\DevTestsRunCommand
Add core command  dev:source-theme:deploy -> Magento\Developer\Console\Command\SourceThemeDeployCommand
Add core command  dev:xml:convert -> Magento\Developer\Console\Command\XmlConverterCommand
Add core command  dev:urn-catalog:generate -> Magento\Developer\Console\Command\XmlCatalogGenerateCommand
Add core command  dev:di:info -> Magento\Developer\Console\Command\DiInfoCommand
Add core command  dev:query-log:enable -> Magento\Developer\Console\Command\QueryLogEnableCommand
Add core command  dev:query-log:disable -> Magento\Developer\Console\Command\QueryLogDisableCommand
Add core command  dev:template-hints:disable -> Magento\Developer\Console\Command\TemplateHintsDisableCommand
Add core command  dev:template-hints:enable -> Magento\Developer\Console\Command\TemplateHintsEnableCommand
Add core command  dev:profiler:disable -> Magento\Developer\Console\Command\ProfilerDisableCommand
Add core command  dev:profiler:enable -> Magento\Developer\Console\Command\ProfilerEnableCommand
Add core command  varnish:vcl:generate -> Magento\PageCache\Console\Command\GenerateVclCommand
Add core command  queue:consumers:start -> Magento\MessageQueue\Console\StartConsumerCommand
Add core command  queue:consumers:list -> Magento\MessageQueue\Console\ConsumerListCommand
Add core command  newrelic:create:deploy-marker -> Magento\NewRelicReporting\Console\Command\DeployMarker
Add core command  setup:db-schema:add-slave -> Magento\ResourceConnections\Console\Command\AddSlave
Add core command  setup:db-schema:split-quote -> Magento\ScalableCheckout\Console\Command\SplitQuote
Add core command  setup:db-schema:split-sales -> Magento\ScalableOms\Console\Command\SplitSales
Add core command  support:utility:check -> Magento\Support\Console\Command\UtilityCheckCommand
Add core command  support:utility:paths -> Magento\Support\Console\Command\UtilityPathsCommand
Add core command  support:backup:db -> Magento\Support\Console\Command\BackupDbCommand
Add core command  support:backup:code -> Magento\Support\Console\Command\BackupCodeCommand
Add core command  i18n:uninstall -> Magento\Translation\Console\Command\UninstallLanguageCommand
Add core command  sampledata:deploy -> Magento\SampleData\Console\Command\SampleDataDeployCommand
Add core command  sampledata:reset -> Magento\SampleData\Console\Command\SampleDataResetCommand
Add core command  sampledata:remove -> Magento\SampleData\Console\Command\SampleDataRemoveCommand
Add command  admin:notifications -> N98\Magento\Command\Admin\NotificationsCommand
Add command  admin:user:list -> N98\Magento\Command\Admin\User\ListCommand
Add command  admin:user:delete -> N98\Magento\Command\Admin\User\DeleteUserCommand
Add command  admin:user:change-password -> N98\Magento\Command\Admin\User\ChangePasswordCommand
Add command  cache:clean -> N98\Magento\Command\Cache\CleanCommand
Add command  cache:disable -> N98\Magento\Command\Cache\DisableCommand
Add command  cache:enable -> N98\Magento\Command\Cache\EnableCommand
Add command  cache:flush -> N98\Magento\Command\Cache\FlushCommand
Add command  cache:list -> N98\Magento\Command\Cache\ListCommand
Add command  cache:report -> N98\Magento\Command\Cache\ReportCommand
Add command  cache:view -> N98\Magento\Command\Cache\ViewCommand
Add command  config:store:delete -> N98\Magento\Command\Config\Store\DeleteCommand
Add command  config:store:get -> N98\Magento\Command\Config\Store\GetCommand
Add command  config:store:set -> N98\Magento\Command\Config\Store\SetCommand
Add command  config:data:acl -> N98\Magento\Command\Config\Data\AclCommand
Add command  config:data:di -> N98\Magento\Command\Config\Data\DiCommand
Add command  customer:create -> N98\Magento\Command\Customer\CreateCommand
Add command  customer:change-password -> N98\Magento\Command\Customer\ChangePasswordCommand
Add command  customer:info -> N98\Magento\Command\Customer\InfoCommand
Add command  customer:list -> N98\Magento\Command\Customer\ListCommand
Add command  db:console -> N98\Magento\Command\Database\ConsoleCommand
Add command  db:create -> N98\Magento\Command\Database\CreateCommand
Add command  db:drop -> N98\Magento\Command\Database\DropCommand
Add command  db:dump -> N98\Magento\Command\Database\DumpCommand
Add command  db:import -> N98\Magento\Command\Database\ImportCommand
Add command  db:info -> N98\Magento\Command\Database\InfoCommand
Add command  db:query -> N98\Magento\Command\Database\QueryCommand
Add command  db:variables -> N98\Magento\Command\Database\VariablesCommand
Add command  db:status -> N98\Magento\Command\Database\StatusCommand
Add command  db:maintain:check-tables -> N98\Magento\Command\Database\Maintain\CheckTablesCommand
Add command  db:info -> N98\Magento\Command\Database\InfoCommand
Add command  design:demo-notice -> N98\Magento\Command\Design\DemoNoticeCommand
Add command  dev:asset:clear -> N98\Magento\Command\Developer\Asset\ClearCommand
Add command  dev:console -> N98\Magento\Command\Developer\ConsoleCommand
Add command  dev:module:create -> N98\Magento\Command\Developer\Module\CreateCommand
Add command  dev:report:count -> N98\Magento\Command\Developer\Report\CountCommand
Add command  dev:symlinks -> N98\Magento\Command\Developer\SymlinksCommand
Add command  dev:template-hints-blocks -> N98\Magento\Command\Developer\TemplateHintsBlocksCommand
Add command  dev:template-hints -> N98\Magento\Command\Developer\TemplateHintsCommand
Add command  dev:theme:list -> N98\Magento\Command\Developer\Theme\ListCommand
Add command  eav:attribute:remove -> N98\Magento\Command\Eav\Attribute\RemoveCommand
Add command  eav:attribute:list -> N98\Magento\Command\Eav\Attribute\ListCommand
Add command  eav:attribute:view -> N98\Magento\Command\Eav\Attribute\ViewCommand
Add command  generation:flush -> N98\Magento\Command\Generation\FlushCommand
Add command  giftcard:pool:generate -> N98\Magento\Command\GiftCard\Pool\GenerateCommand
Add command  giftcard:create -> N98\Magento\Command\GiftCard\CreateCommand
Add command  giftcard:info -> N98\Magento\Command\GiftCard\InfoCommand
Add command  giftcard:remove -> N98\Magento\Command\GiftCard\RemoveCommand
Add command  media:dump -> N98\Magento\Command\Media\DumpCommand
Add command  open-browser -> N98\Magento\Command\OpenBrowserCommand
Add command  search:engine:list -> N98\Magento\Command\SearchEngine\ListCommand
Add command  script:repo:list -> N98\Magento\Command\Script\Repository\ListCommand
Add command  script:repo:run -> N98\Magento\Command\Script\Repository\RunCommand
Add command  sys:check -> N98\Magento\Command\System\CheckCommand
Add command  sys:cron:history -> N98\Magento\Command\System\Cron\HistoryCommand
Add command  sys:cron:list -> N98\Magento\Command\System\Cron\ListCommand
Add command  sys:cron:run -> N98\Magento\Command\System\Cron\RunCommand
Add command  sys:cron:schedule -> N98\Magento\Command\System\Cron\ScheduleCommand
Add command  sys:info -> N98\Magento\Command\System\InfoCommand
Add command  sys:maintenance -> N98\Magento\Command\System\MaintenanceCommand
Add command  sys:setup:change-version -> N98\Magento\Command\System\Setup\ChangeVersionCommand
Add command  sys:setup:compare-versions -> N98\Magento\Command\System\Setup\CompareVersionsCommand
Add command  sys:setup:downgrade-versions -> N98\Magento\Command\System\Setup\DowngradeVersionsCommand
Add command  sys:store:list -> N98\Magento\Command\System\Store\ListCommand
Add command  sys:url:list -> N98\Magento\Command\System\Url\ListCommand
Add command  sys:store:config:base-url:list -> N98\Magento\Command\System\Store\Config\BaseUrlListCommand
Add command  sys:website:list -> N98\Magento\Command\System\Website\ListCommand
Add command  index:list -> N98\Magento\Command\Indexer\ListCommand
Add command  index:trigger:recreate -> N98\Magento\Command\Indexer\RecreateTriggersCommand
Add command  install -> N98\Magento\Command\Installer\InstallCommand
Add command  dev:module:list -> N98\Magento\Command\Developer\Module\ListCommand
Add command  dev:module:observer:list -> N98\Magento\Command\Developer\Module\Observer\ListCommand
Add command  script -> N98\Magento\Command\ScriptCommand
Add command  shell -> N98\Magento\Command\ShellCommand
Add command  self-update -> N98\Magento\Command\SelfUpdateCommand
Changed CWD to /path/to/m226ee
Reading ./composer.json
Loading config file /path/to/m226ee/var/composer_home/auth.json
Loading config file ./composer.json
Failed to initialize global composer: Composer could not find the config file: /path/to/m226ee/var/composer_home/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Reading /path/to/m226ee/vendor/composer/installed.json
Loading plugin MagentoHackathon\Composer\Magento\Plugin_composer_tmp1
activate magento plugin
Running 1.4.1 (2017-03-10 09:29:45) with PHP 7.1.24 on Darwin / 18.2.0
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
PHP Fatal error:  Uncaught Error: Undefined class constant 'PRE_COMMAND_RUN' in phar:///usr/local/bin/mr2/vendor/composer/composer/src/Composer/Command/BaseCommand.php:136
Stack trace:
#0 /path/to/m226ee/vendor/symfony/console/Command/Command.php(211): Composer\Command\BaseCommand->initialize(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#1 phar:///usr/local/bin/mr2/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 phar:///usr/local/bin/mr2/vendor/symfony/console/Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Composer\Command\RequireCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /path/to/m226ee/vendor/composer/composer/src/Composer/Console/Application.php(227): Symfo in phar:///usr/local/bin/mr2/vendor/composer/composer/src/Composer/Command/BaseCommand.php on line 136

Fatal error: Uncaught Error: Undefined class constant 'PRE_COMMAND_RUN' in phar:///usr/local/bin/mr2/vendor/composer/composer/src/Composer/Command/BaseCommand.php on line 136

Error: Undefined class constant 'PRE_COMMAND_RUN' in phar:///usr/local/bin/mr2/vendor/composer/composer/src/Composer/Command/BaseCommand.php on line 136

Call Stack:
    0.0005     352392   1. {main}() /usr/local/bin/mr2:0
    0.0302    2134672   2. N98\Magento\Application->run() /usr/local/bin/mr2:8
    1.5071   38751168   3. N98\Magento\Application->run() phar:///usr/local/bin/mr2/src/N98/Magento/Application.php:326
    1.5071   38751168   4. N98\Magento\Application->doRun() phar:///usr/local/bin/mr2/vendor/symfony/console/Application.php:117
    1.5685   42240088   5. N98\Magento\Application->doRun() phar:///usr/local/bin/mr2/src/N98/Magento/Application.php:244
    1.5687   42305624   6. N98\Magento\Application->doRunCommand() phar:///usr/local/bin/mr2/vendor/symfony/console/Application.php:185
```

**Comment by cmuench** [comment]
I downgraded the bundled composer in the phar file to 1.4.3 which should be compatible with Magento 2.2.7.
Can you verify the command in your installation.
Please update to development version with "n98-magerun2.phar self-update --unstable".

**Comment by JDavidVR** [comment]
Hi! @cmuench  it is working well on m2.2.7ee here are useful information, I will test with 2.3 too and will update this post.

Thank you!

```
$ php mr2.phar self-update --unstable
Updating to version 3.0.0.
Downloading (100%)         

RECENT CHANGES
==============


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!! DEVELOPMENT VERSION. DO NOT USE IN PRODUCTION !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


---------------------------------
Successfully updated n98-magerun2
---------------------------------
```

```
php mr2.phar sample:deploy
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 25 installs, 0 updates, 0 removals
  - Installing magento/module-catalog-sample-data (100.2.0): Loading from cache
  - Installing magento/module-bundle-sample-data (100.2.0): Loading from cache
  - Installing magento/module-customer-sample-data (100.2.0): Loading from cache
```

**Comment by cmuench** [comment]
@JDavidVR I was able to run the install sample data command in a fresh Magento Commerce 2.3.0.

**Comment by cmuench** [comment]
The fix is deployed as v3.0.1.

**Comment by karuna2828** [comment]
Hi everyone,
I get the same.
I want to upgrade my version 2.3.4 to 2.3.5 in Magento EE .
I run 2 commands 
1. sudo composer require magento/product-enterprise-edition 2.3.5 --no-update
2.sudo composer update
getting an error in composer update 

![image](https://user-images.githubusercontent.com/64192247/80075105-ca470880-8567-11ea-8392-a83bf61a4339.png)

please help me to resolve this error.

**Comment by cmuench** [comment]
@karuna2828 Your problem is a core update problem of Magento. That looks not like a issue of n98-magerun2. Please open an issue in official Magento repository.

**Comment by munkhulzii** [comment]
@karuna2828 composer self-update solved this problem for me. 

btw. Why are you using sudo for composer?

**Comment by shintusingh** [comment]
@munkhulzii I am also getting this error while upgrading Magento to 2.3.5. Please help how to run self-update in Magento

**Comment by cmuench** [comment]
@shintusingh That command is part of Magento Core. Is n98-magerun2 part of your upgrade process?

**Comment by omelandr** [comment]
You have old composer
Need to do:

composer -V
sudo apt remove composer
cd /tmp
wget http://getcomposer.org/download/1.10.5/composer.phar
########################## Alternative ###########
#curl -Ss http://getcomposer.org/download/1.10.5/composer.phar -o composer.phar
##################################################
php composer.phar -V
sudo mv composer.phar /usr/bin/composer
sudo chmod 750 /usr/bin/composer
composer -V
