### ISSUE TITLE
Db:dump without filename will throw an error

### ISSUE THREAD

**Issue by frostblogNet** [netz98/n98-magerun2#527]
n98-magerun2 4.0.3
magento 2.3.4 

When n98-magerun2 db:dump is called without a filename the following error will be shown.

`PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\Component\Console\Question\Question::getAutocompleterCallback() in phar:///opt/n98-magerun2/n98-magerun2.phar/vendor/symfony/console/Helper/QuestionHelper.php:119
Stack trace:
#0 phar:///opt/n98-magerun2/n98-magerun2.phar/vendor/symfony/console/Helper/QuestionHelper.php(81): Symfony\Component\Console\Helper\QuestionHelper->doAsk(Object(Symfony\Component\Console\Output\StreamOutput), Object(Symfony\Component\Console\Question\Question))
#1 phar:///opt/n98-magerun2/n98-magerun2.phar/src/N98/Magento/Command/Database/DumpCommand.php(500): Symfony\Component\Console\Helper\QuestionHelper->ask(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\StreamOutput), Object(Symfony\Component\Console\Question\Question))
#2 phar:///opt/n98-magerun2/n98-magerun2.phar/src/N98/Magento/Command/Database/DumpCommand.php(266): N98\Magento\Command\Database\DumpCommand->getFileName(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Co in phar:///opt/n98-magerun2/n98-magerun2.phar/vendor/symfony/console/Helper/QuestionHelper.php on line 119`

As a workaroud you can provide the filename directly after db:dump.

**Comment by frostblogNet** [comment]
Same issue as in https://github.com/netz98/n98-magerun2/issues/521
