### ISSUE TITLE
Area Code not set when trying to send emails from cli - caused by second App\State instance

### ISSUE THREAD

**Issue by pointia** [netz98/n98-magerun2#627]
## Describe the bug

When trying to send the translated order email from command line I get the following error: Return value of Magento\Framework\Filter\DirectiveProcessor\TemplateDirective::process() must be of the type string, object returned

This is caused by an exception that is caught here: \Magento\Email\Model\Template\Filter::filter
The exception that is thrown is furthermore raised in Magento\Theme\Model\View\Design\Proxy->getDesignParams() -> Magento\Theme\Model\View\Design->getArea() with the \Magento\Framework\App\State::getAreaCode exception

I've debugged into it and found out that a second \Magento\Framework\App\State instance is created by n98magerun2.

If I execute the command using bin/magento it works.

## Expected behaviour

Order Email should be sent without any exception.

## Steps to reproduce the issue

1. Add a new console command that is running the frontend area with the translation loaded
``` 
try {
            $this->state->getAreaCode();
        } catch (\Exception $exception) {
            $this->state->setAreaCode(Area::AREA_FRONTEND);
        }
        $this->areaList->getArea(Area::AREA_FRONTEND)->load(Area::PART_TRANSLATE);
```

2.  Load an order and try to send the order email with the following command:
```
/** use Magento\Sales\Model\Order\Email\Sender\OrderSender; **/
$this->emailSender->send($order, true);
```

## Technical details

- Host Machine OS (Windows/Linux/Mac):
Ubuntu 18.04 , Magento 2.3.5-p1, Magerun2 4.3.0
## Possible Fix

For now we use bin/magento

## Additional context

<details>
<summary>Here ist the initial stacktrace that caused the error:</summary>

``` 
#1 /var/www/staging/releases/20200925084558/vendor/magento/module-theme/Model/View/Design.php(275): Magento\Theme\Model\View\Design->getArea()
#2 /var/www/staging/releases/20200925084558/generated/code/Magento/Theme/Model/View/Design/Proxy.php(167): Magento\Theme\Model\View\Design->getDesignParams()
#3 /var/www/staging/releases/20200925084558/vendor/magento/framework/View/Asset/Repository.php(199): Magento\Theme\Model\View\Design\Proxy->getDesignParams()
#4 /var/www/staging/releases/20200925084558/vendor/magento/framework/View/Asset/Repository.php(137): Magento\Framework\View\Asset\Repository->getDefaultParameter('area')
#5 /var/www/staging/releases/20200925084558/vendor/magento/framework/View/Asset/Repository.php(254): Magento\Framework\View\Asset\Repository->updateDesignParams(Array)
#6 /var/www/staging/releases/20200925084558/vendor/magento/module-email/Model/Template/Css/Processor.php(59): Magento\Framework\View\Asset\Repository->getStaticViewFileContext()
#7 /var/www/staging/releases/20200925084558/vendor/magento/module-email/Model/Template/Css/Processor.php(42): Magento\Email\Model\Template\Css\Processor->getPlaceholderValue('base_url_path')
#8 /var/www/staging/releases/20200925084558/vendor/magento/module-email/Model/Template/Filter.php(896): Magento\Email\Model\Template\Css\Processor->process('@import url("{{...')
#9 [internal function]: Magento\Email\Model\Template\Filter->cssDirective(Array)
#10 /var/www/staging/releases/20200925084558/vendor/magento/framework/Filter/DirectiveProcessor/LegacyDirective.php(42): ReflectionMethod->invokeArgs(Object(Magento\Email\Model\Template\Filter\Interceptor), Array)
#11 /var/www/staging/releases/20200925084558/vendor/magento/framework/Filter/Template.php(184): Magento\Framework\Filter\DirectiveProcessor\LegacyDirective->process(Array, Object(Magento\Email\Model\Template\Filter\Interceptor), Array)
#12 /var/www/staging/releases/20200925084558/vendor/magento/module-email/Model/Template/Filter.php(1080): Magento\Framework\Filter\Template->filter('<!DOCTYPE html ...')
#13 /var/www/staging/releases/20200925084558/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Email\Model\Template\Filter->filter('<!DOCTYPE html ...')
#14 /var/www/staging/releases/20200925084558/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Email\Model\Template\Filter\Interceptor->___callParent('filter', Array)
#15 /var/www/staging/releases/20200925084558/vendor/aheadworks/module-rma/Plugin/Model/EmailTemplateFilterPlugin.php(28): Magento\Email\Model\Template\Filter\Interceptor->Magento\Framework\Interception\{closure}('<!DOCTYPE html ...')
#16 /var/www/staging/releases/20200925084558/vendor/magento/framework/Interception/Interceptor.php(135): Aheadworks\Rma\Plugin\Model\EmailTemplateFilterPlugin->aroundFilter(Object(Magento\Email\Model\Template\Filter\Interceptor), Object(Closure), '<!DOCTYPE html ...')
#17 /var/www/staging/releases/20200925084558/app/code/Magezon/PageBuilder/Plugin/Filter/Template.php(39): Magento\Email\Model\Template\Filter\Interceptor->Magento\Framework\Interception\{closure}('<!DOCTYPE html ...')
#18 /var/www/staging/releases/20200925084558/vendor/magento/framework/Interception/Interceptor.php(135): Magezon\PageBuilder\Plugin\Filter\Template->aroundFilter(Object(Magento\Email\Model\Template\Filter\Interceptor), Object(Closure), '<!DOCTYPE html ...')
#19 /var/www/staging/releases/20200925084558/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Email\Model\Template\Filter\Interceptor->Magento\Framework\Interception\{closure}('<!DOCTYPE html ...')
#20 /var/www/staging/releases/20200925084558/generated/code/Magento/Email/Model/Template/Filter/Interceptor.php(26): Magento\Email\Model\Template\Filter\Interceptor->___callPlugins('filter', Array, NULL)
#21 /var/www/staging/releases/20200925084558/vendor/magento/module-email/Model/AbstractTemplate.php(369): Magento\Email\Model\Template\Filter\Interceptor->filter('<!DOCTYPE html ...')
#22 /var/www/staging/releases/20200925084558/vendor/magento/module-email/Model/AbstractTemplate.php(247): Magento\Email\Model\AbstractTemplate->getProcessedTemplate(Array)
#23 [internal function]: Magento\Email\Model\AbstractTemplate->getTemplateContent('design/email/he...', Array)
#24 /var/www/staging/releases/20200925084558/vendor/magento/framework/Filter/DirectiveProcessor/TemplateDirective.php(65): call_user_func(Array, 'design/email/he...', Array)
#25 /var/www/staging/releases/20200925084558/vendor/magento/framework/Filter/Template.php(184): Magento\Framework\Filter\DirectiveProcessor\TemplateDirective->process(Array, Object(Magento\Email\Model\Template\Filter\Interceptor), Array)
#26 /var/www/staging/releases/20200925084558/vendor/magento/module-email/Model/Template/Filter.php(1080): Magento\Framework\Filter\Template->filter('{{template conf...')
#27 /var/www/staging/releases/20200925084558/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Email\Model\Template\Filter->filter('{{template conf...')
#28 /var/www/staging/releases/20200925084558/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Email\Model\Template\Filter\Interceptor->___callParent('filter', Array)
#29 /var/www/staging/releases/20200925084558/vendor/aheadworks/module-rma/Plugin/Model/EmailTemplateFilterPlugin.php(28): Magento\Email\Model\Template\Filter\Interceptor->Magento\Framework\Interception\{closure}('{{template conf...')
#30 /var/www/staging/releases/20200925084558/vendor/magento/framework/Interception/Interceptor.php(135): Aheadworks\Rma\Plugin\Model\EmailTemplateFilterPlugin->aroundFilter(Object(Magento\Email\Model\Template\Filter\Interceptor), Object(Closure), '{{template conf...')
#31 /var/www/staging/releases/20200925084558/app/code/Magezon/PageBuilder/Plugin/Filter/Template.php(39): Magento\Email\Model\Template\Filter\Interceptor->Magento\Framework\Interception\{closure}('{{template conf...')
#32 /var/www/staging/releases/20200925084558/vendor/magento/framework/Interception/Interceptor.php(135): Magezon\PageBuilder\Plugin\Filter\Template->aroundFilter(Object(Magento\Email\Model\Template\Filter\Interceptor), Object(Closure), '{{template conf...')
#33 /var/www/staging/releases/20200925084558/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Email\Model\Template\Filter\Interceptor->Magento\Framework\Interception\{closure}('{{template conf...')
#34 /var/www/staging/releases/20200925084558/generated/code/Magento/Email/Model/Template/Filter/Interceptor.php(26): Magento\Email\Model\Template\Filter\Interceptor->___callPlugins('filter', Array, NULL)
#35 /var/www/staging/releases/20200925084558/vendor/magento/module-email/Model/AbstractTemplate.php(369): Magento\Email\Model\Template\Filter\Interceptor->filter('{{template conf...')
#36 /var/www/staging/releases/20200925084558/vendor/magento/module-email/Model/Template.php(387): Magento\Email\Model\AbstractTemplate->getProcessedTemplate(Array)
#37 /var/www/staging/releases/20200925084558/vendor/mageplaza/module-pdf-invoice/Model/Template/TransportBuilder.php(279): Magento\Email\Model\Template->processTemplate()
#38 /var/www/staging/releases/20200925084558/vendor/magento/framework/Mail/Template/TransportBuilder.php(337): Mageplaza\PdfInvoice\Model\Template\TransportBuilder->prepareMessage()
#39 /var/www/staging/releases/20200925084558/vendor/magento/module-sales/Model/Order/Email/SenderBuilder.php(74): Magento\Framework\Mail\Template\TransportBuilder->getTransport()
#40 /var/www/staging/releases/20200925084558/vendor/mageplaza/module-pdf-invoice/Model/Template/SenderBuilder.php(108): Magento\Sales\Model\Order\Email\SenderBuilder->send()
#41 /var/www/staging/releases/20200925084558/vendor/magento/module-sales/Model/Order/Email/Sender.php(86): Mageplaza\PdfInvoice\Model\Template\SenderBuilder->send()
#42 /var/www/staging/releases/20200925084558/vendor/magento/module-sales/Model/Order/Email/Sender/OrderSender.php(103): Magento\Sales\Model\Order\Email\Sender->checkAndSend(Object(Magento\Sales\Model\Order\Interceptor))
#43 /var/www/staging/releases/20200925084558/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Model\Order\Email\Sender\OrderSender->send(Object(Magento\Sales\Model\Order\Interceptor), true)
#44 /var/www/staging/releases/20200925084558/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Model\Order\Email\Sender\OrderSender\Interceptor->___callParent('send', Array)
#45 /var/www/staging/releases/20200925084558/app/code/CopeX/AxOrder/Plugin/DontSendOrderEmailBeforeExport.php(31): Magento\Sales\Model\Order\Email\Sender\OrderSender\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Sales\Model\Order\Interceptor), true)
#46 /var/www/staging/releases/20200925084558/vendor/magento/framework/Interception/Interceptor.php(135): CopeX\AxOrder\Plugin\DontSendOrderEmailBeforeExport->aroundSend(Object(Magento\Sales\Model\Order\Email\Sender\OrderSender\Interceptor), Object(Closure), Object(Magento\Sales\Model\Order\Interceptor), true)
#47 /var/www/staging/releases/20200925084558/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\Order\Email\Sender\OrderSender\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Sales\Model\Order\Interceptor), true)
#48 /var/www/staging/releases/20200925084558/generated/code/Magento/Sales/Model/Order/Email/Sender/OrderSender/Interceptor.php(26): Magento\Sales\Model\Order\Email\Sender\OrderSender\Interceptor->___callPlugins('send', Array, NULL)
#49 /var/www/staging/releases/20200925084558/app/code/CopeX/AxOrder/Cron/Order.php(126): Magento\Sales\Model\Order\Email\Sender\OrderSender\Interceptor->send(Object(Magento\Sales\Model\Order\Interceptor), true)
```

</details>

<details>
<summary>Stacktrace that instantiates the second instance of App\State </summary>

```
#0 /var/www/staging/releases/20200925084558/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(121): Magento\Framework\App\State->__construct(Object(Magento\Framework\Config\Scope), 'production')
#1 /var/www/staging/releases/20200925084558/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array)
#2 /var/www/staging/releases/20200925084558/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Framewo...')
#3 /var/www/staging/releases/20200925084558/vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\Framework\ObjectManager\Factory\Compiled->get('Magento\\Framewo...')
#4 /var/www/staging/releases/20200925084558/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Develop...')
#5 /var/www/staging/releases/20200925084558/vendor/magento/framework/ObjectManager/Factory/Compiled.php(125): Magento\Framework\ObjectManager\Factory\Compiled->get('Magento\\Develop...')
#6 /var/www/staging/releases/20200925084558/vendor/magento/framework/ObjectManager/Factory/Compiled.php(86): Magento\Framework\ObjectManager\Factory\Compiled->parseArray(Array)
#7 /var/www/staging/releases/20200925084558/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Framewo...')
#8 /var/www/staging/releases/20200925084558/vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\Framework\ObjectManager\Factory\Compiled->get('Magento\\Framewo...')
#9 /var/www/staging/releases/20200925084558/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Framewo...')
#10 /var/www/staging/releases/20200925084558/vendor/magento/framework/ObjectManager/Factory/Compiled.php(79): Magento\Framework\ObjectManager\Factory\Compiled->get('Magento\\Framewo...')
#11 /var/www/staging/releases/20200925084558/vendor/magento/framework/ObjectManager/ObjectManager.php(56): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Framewo...', Array)
#12 /var/www/staging/releases/20200925084558/vendor/magento/framework/App/Cache/Frontend/Factory.php(197): Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Framewo...', Array)
#13 /var/www/staging/releases/20200925084558/vendor/magento/framework/App/Cache/Frontend/Factory.php(161): Magento\Framework\App\Cache\Frontend\Factory->_applyDecorators(Object(Magento\Framework\Cache\Frontend\Decorator\TagScope))
#14 /var/www/staging/releases/20200925084558/vendor/magento/framework/App/Cache/Frontend/Pool.php(69): Magento\Framework\App\Cache\Frontend\Factory->create(Array)
#15 /var/www/staging/releases/20200925084558/vendor/magento/framework/App/Cache/Frontend/Pool.php(151): Magento\Framework\App\Cache\Frontend\Pool->_initialize()
#16 /var/www/staging/releases/20200925084558/vendor/magento/framework/App/Cache/Type/FrontendPool.php(87): Magento\Framework\App\Cache\Frontend\Pool->get('default')
#17 /var/www/staging/releases/20200925084558/vendor/magento/framework/App/Interception/Cache/CompiledConfig.php(29): Magento\Framework\App\Cache\Type\FrontendPool->get('compiled_config')
#18 /var/www/staging/releases/20200925084558/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(121): Magento\Framework\App\Interception\Cache\CompiledConfig->__construct(Object(Magento\Framework\App\Cache\Type\FrontendPool))
#19 /var/www/staging/releases/20200925084558/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...', Array)
#20 /var/www/staging/releases/20200925084558/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Compiled->create('Magento\\Framewo...')
#21 /var/www/staging/releases/20200925084558/vendor/magento/framework/App/ObjectManager/Environment/Compiled.php(117): Magento\Framework\ObjectManager\ObjectManager->get('Magento\\Framewo...')
#22 /var/www/staging/releases/20200925084558/vendor/magento/framework/App/ObjectManagerFactory.php(191): Magento\Framework\App\ObjectManager\Environment\Compiled->configureObjectManager(Object(Magento\Framework\Interception\ObjectManager\Config\Compiled), Array)
#23 /var/www/staging/releases/20200925084558/vendor/magento/framework/App/Bootstrap.php(211): Magento\Framework\App\ObjectManagerFactory->create(Array)
#24 /var/www/staging/releases/20200925084558/vendor/magento/framework/App/Bootstrap.php(126): Magento\Framework\App\Bootstrap->__construct(Object(Magento\Framework\App\ObjectManagerFactory), '/var/www/stagin...', Array)
#25 phar:///var/www/staging/releases/20200925084558/bin/n98-magerun2/src/N98/Magento/Application/Magento2Initializer.php(60): Magento\Framework\App\Bootstrap::create('/var/www/stagin...', Array)
#26 phar:///var/www/staging/releases/20200925084558/bin/n98-magerun2/src/N98/Magento/Application.php(246): N98\Magento\Application\Magento2Initializer->init('/var/www/stagin...')
#27 phar:///var/www/staging/releases/20200925084558/bin/n98-magerun2/src/N98/Magento/Application/Console/EventSubscriber/CheckCompatibility.php(46): N98\Magento\Application->initMagento(true)
#28 phar:///var/www/staging/releases/20200925084558/bin/n98-magerun2/vendor/symfony/event-dispatcher/EventDispatcher.php(264): N98\Magento\Application\Console\EventSubscriber\CheckCompatibility->checkCompatibility(Object(Symfony\Component\Console\Event\ConsoleEvent), 'n98-magerun.app...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#29 phar:///var/www/staging/releases/20200925084558/bin/n98-magerun2/vendor/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'n98-magerun.app...', Object(Symfony\Component\Console\Event\ConsoleEvent))
#30 phar:///var/www/staging/releases/20200925084558/bin/n98-magerun2/vendor/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners(Array, 'n98-magerun.app...', Object(Symfony\Component\Console\Event\ConsoleEvent))
#31 phar:///var/www/staging/releases/20200925084558/bin/n98-magerun2/src/N98/Magento/Application.php(224): Symfony\Component\EventDispatcher\EventDispatcher->dispatch(Object(Symfony\Component\Console\Event\ConsoleEvent), 'n98-magerun.app...')
#32 phar:///var/www/staging/releases/20200925084558/bin/n98-magerun2/vendor/symfony/console/Application.php(147): N98\Magento\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#33 phar:///var/www/staging/releases/20200925084558/bin/n98-magerun2/src/N98/Magento/Application.php(329): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#34 /var/www/staging/releases/20200925084558/bin/n98-magerun2(8): N98\Magento\Application->run()

```

</details>

Thanks for providing such a great tool! 
I hope I've explained the error enough. I've also checked the other issues but I'm not quite sure if this is covered by another one already.

**Comment by cmuench** [comment]
@pointia Thanks for reporting. That's a known issue here. I think to fix this, we need to refactor some commands. So it needs some time to find the best solution.

**Comment by cmuench** [comment]
@pointia We have refactored the way we call Magento Core Commands.
That can be tested in develop branch.
The new version should also fix this issue. The issue is very old and we do not support Magento 2.3.5 anymore.
Hope your shop is not anymore on 2.3.5 :-)
I will close this issue. If the error is still reproducible, please re-open.
