### ISSUE TITLE
selfupdate is broken in v4.6.0

### ISSUE THREAD

**Issue by jeroenvermeulen** [netz98/n98-magerun2#778]
## Describe the bug

`selfupdate` is broken in v4.6.0

Error:
```
Fatal error: Uncaught ArgumentCountError: Too few arguments to function Composer\Util\RemoteFilesystem::__construct(), 1 passed in phar:///home/server/n98-magerun2.phar/src/N98/Magento/Command/SelfUpdateCommand.php on line 82 and at least 2 expected in phar:///home/server/n98-magerun2.phar/vendor/composer/composer/src/Composer/Util/RemoteFilesystem.php:61
Stack trace:
#0 phar:///home/server/n98-magerun2.phar/src/N98/Magento/Command/SelfUpdateCommand.php(82): Composer\Util\RemoteFilesystem->__construct(Object(Composer\IO\ConsoleIO))
#1 phar:///home/server/n98-magerun2.phar/vendor/symfony/console/Command/Command.php(255): N98\Magento\Command\SelfUpdateCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 phar:///home/server/n98-magerun2.phar/src/N98/Magento/Command/AbstractMagentoCommand.php(363): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3  in phar:///home/server/n98-magerun2.phar/vendor/composer/composer/src/Composer/Util/RemoteFilesystem.php on line 61
```

## Expected behaviour

Update to the latest version, or report `You are using the latest n98-magerun version.`

## Steps to reproduce the issue

```
server@star:~$ php -v
PHP 7.4.20 (cli) (built: Jun  4 2021 21:24:55) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.20, Copyright (c), by Zend Technologies

server@star:~$ wget --no-verbose http://files.magerun.net/n98-magerun2-latest.phar -O n98-magerun2.phar
2021-06-14 09:32:49 URL:https://files.magerun.net/n98-magerun2-latest.phar [5828107/5828107] -> "n98-magerun2.phar" [1]

server@star:~$ chmod +x n98-magerun2.phar

server@star:~$ ./n98-magerun2.phar --version
n98-magerun2 4.6.0 by netz98 GmbH

server@star:~$ ./n98-magerun2.phar selfupdate

Fatal error: Uncaught ArgumentCountError: Too few arguments to function Composer\Util\RemoteFilesystem::__construct(), 1 passed in phar:///home/server/n98-magerun2.phar/src/N98/Magento/Command/SelfUpdateCommand.php on line 82 and at least 2 expected in phar:///home/server/n98-magerun2.phar/vendor/composer/composer/src/Composer/Util/RemoteFilesystem.php:61
Stack trace:
#0 phar:///home/server/n98-magerun2.phar/src/N98/Magento/Command/SelfUpdateCommand.php(82): Composer\Util\RemoteFilesystem->__construct(Object(Composer\IO\ConsoleIO))
#1 phar:///home/server/n98-magerun2.phar/vendor/symfony/console/Command/Command.php(255): N98\Magento\Command\SelfUpdateCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 phar:///home/server/n98-magerun2.phar/src/N98/Magento/Command/AbstractMagentoCommand.php(363): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3  in phar:///home/server/n98-magerun2.phar/vendor/composer/composer/src/Composer/Util/RemoteFilesystem.php on line 61
```

## Technical details

Ubuntu 20.04 LTS (Focal)

## Additional context

On our hosting servers we are installing N98-Magerun and N98-Magerun2 by default. We run `selfupdate` every day. So far this has almost always worked. Since `2021-06-14 06:02` it is broken on all servers.

**Comment by cmuench** [comment]
@jeroenvermeulen sorry for the issue. I will provide a hotfix release.

**Comment by cmuench** [comment]
@jeroenvermeulen Hotfix is released as v4.6.1.

**Comment by jeroenvermeulen** [comment]
Wow that is fast @cmuench, really impressive.
It works again, case closed!

**Comment by cmuench** [comment]
Yes, that was a critical bug.
I try to add a github action to prevent that in the future.

**Comment by cmuench** [comment]
github action FTW!

![grafik](https://user-images.githubusercontent.com/211294/121861093-d22cb380-ccf9-11eb-8ba1-a9fc703b33cf.png)

**Comment by cmuench** [comment]
Maybe I find also a solution for the broken signature.
