### ISSUE TITLE
sampledata:deploy returns composer error, bin/magento works (Composer 1)

### ISSUE THREAD

**Issue by jeroenvermeulen** [netz98/n98-magerun2#789]
## Describe the bug

n98-magerun2 version: 4.6.1
Magento version: 2.4.2-p1
Composer version 1.10.22 2021-04-27 13:10:45

`n98-magerun2 sampledata:deploy` doen not work while `bin/magento sampledata:deploy` does work.

## Expected behaviour

Deploy sample data.

## Steps to reproduce the issue

```
~/magento2$ n98-magerun2  sampledata:deploy

Fatal error: Uncaught Error: Call to undefined method Composer\Composer::setLoop() in phar:///usr/local/bin/n98-magerun2.phar/vendor/composer/composer/src/Composer/Factory.php:357
Stack trace:
#0 phar:///usr/local/bin/n98-magerun2.phar/vendor/composer/composer/src/Composer/Factory.php(604): Composer\Factory->createComposer(Object(Composer\IO\BufferIO), Array, false)
#1 /home/jeroenvm/magento2/vendor/magento/framework/Composer/ComposerFactory.php(47): Composer\Factory::create(Object(Composer\IO\BufferIO), '/home/jeroenvm/...')
#2 /home/jeroenvm/magento2/vendor/magento/framework/Composer/ComposerInformation.php(368): Magento\Framework\Composer\ComposerFactory->create()
#3 /home/jeroenvm/magento2/vendor/magento/framework/Composer/ComposerInformation.php(381): Magento\Framework\Composer\ComposerInformation->getComposer()
#4 /home/jeroenvm/magento2/vendor/magento/framework/Composer/ComposerInformation.php(176): Magento\Framework\Composer\ComposerInformation->getLocker()
#5 /home/jeroenvm/magento2/vendor/magento/module-sample-d in phar:///usr/local/bin/n98-magerun2.phar/vendor/composer/composer/src/Composer/Factory.php on line 357

~/magento2$ bin/magento sampledata:deploy
<warning>Warning from https://repo.packagist.org: Support for Composer 1 is deprecated and some packages will not be available. You should upgrade to Composer 2. See https://blog.packagist.com/deprecating-composer-1-support/</warning>
./composer.json has been updated
Loading composer repositories with package information
<warning>Warning from https://repo.packagist.org: Support for Composer 1 is deprecated and some packages will not be available. You should upgrade to Composer 2. See https://blog.packagist.com/deprecating-composer-1-support/</warning>
Updating dependencies (including require-dev)
Nothing to install or update
<warning>Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.</warning>
<warning>Package laminas/laminas-console is abandoned, you should avoid using it. Use laminas/laminas-cli instead.</warning>
<warning>Package phpunit/php-token-stream is abandoned, you should avoid using it. No replacement was suggested.</warning>
<warning>Package sebastian/finder-facade is abandoned, you should avoid using it. No replacement was suggested.</warning>
Generating autoload files
96 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
PHP CodeSniffer Config installed_paths set to ../../magento/magento-coding-standard,../../phpcompatibility/php-compatibility
```

## Technical details

- Host Machine OS (Windows/Linux/Mac):
Ubuntu 20.04.2 LTS
Linux [hostname] 5.8.0-55-generic # 62~20.04.1-Ubuntu SMP Wed Jun 2 08:55:04 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

## Possible Fix

Because of backwards compatibility our servers are using Composer 1 by default. Developers can use Composer 2.x by calling `composer2`. If that is the cause of this problem and there is no easy way to solve it, N98 could warn the user to switch to Composer 2.

**Comment by cmuench** [comment]
@jeroenvermeulen We have the same issue if run "setup:upgrade" with n98-magerun2.
Maybe we cannot fix that without patching composer in the phar file here.

**Comment by cmuench** [comment]
Problem is not the installed Composer on the server.
There are three Composer sources available but not involved.

- Bundled Composer in Magento
- Bundled Composer in n98-magerun2
- Installed Composer on the server

I try to figure out how we can proceed.

**Comment by jeroenvermeulen** [comment]
It probably does not help but just to be sure I will post some debug info.

Besides the contents of the `phar` files, I find this Composer source:
```
~$ locate 'Composer/Composer.php'
/home/jeroenvm/magento2/var/vendor/composer/composer/src/Composer/Composer.php
/home/jeroenvm/magento2/vendor/composer/composer/src/Composer/Composer.php
```

I already tried to switch to Composer 2, but did not manage to stop https://repo.packagist.org from complaining about me using Composer 1.

Here is some info about our default location of Composer:
```
~$ (set -o posix; set) | grep COMPOSER
COMPOSER_ALLOW_XDEBUG=1
COMPOSER_DISABLE_XDEBUG_WARN=1
~$ which composer
/usr/local/bin/composer
~$ readlink -f /usr/local/bin/composer
/usr/local/bin/composer-1.phar
~$ /usr/local/bin/composer-1.phar -V
Composer version 1.10.22 2021-04-27 13:10:45
```

And N98:
```
~$ which n98-magerun2
/usr/local/bin/n98-magerun2
~$ readlink -f /usr/local/bin/n98-magerun2
/usr/local/bin/n98-magerun2.phar
~$ /usr/local/bin/n98-magerun2.phar -V
n98-magerun2 4.6.1 by netz98 GmbH
```

**Comment by cmuench** [comment]
I was able to reproduce the issue.
The problem is that some Magento commands are initialize the bundled Composer in Magento.
If we start that command with n98-magerun2 the Autoloader prefers the Composer bundled in n98-magerun2 phar file.
If we use bin/magento the version bundled with Magento 2 is used.

**Comment by jeroenvermeulen** [comment]
My Magento is also not completely happy with Composer, maybe there is an hint in this error:
```
~/magento2$ bin/magento  setup:upgrade  --keep-generated
Cache types config flushed successfully
Cache cleared successfully
Updating modules:
Cache cleared successfully
Schema creation/updates:
Module 'Magento_AdminAnalytics':
...
Module 'Magento_CompareListGraphQl':
Module 'Magento_ComposerRootUpdatePlugin':
Running data recurring...Reading /home/jeroenvm/magento2/composer.json
Loading config file /home/jeroenvm/magento2/var/composer_home/auth.json
Loading config file /home/jeroenvm/magento2/composer.json
Failed to initialize global composer: Composer could not find the config file: /home/jeroenvm/magento2/var/composer_home/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Reading /home/jeroenvm/magento2/vendor/composer/installed.json
Reading /home/jeroenvm/magento2/composer.lock
Checking for "magento/composer-root-update-plugin: 1.1.2" for the Web Setup Wizard...
Reading /home/jeroenvm/magento2/var/vendor/magento/composer-root-update-plugin/composer.json
Loading config file /home/jeroenvm/magento2/var/composer_home/auth.json
Loading config file /home/jeroenvm/magento2/var/vendor/magento/composer-root-update-plugin/composer.json
No Web Setup Wizard update needed for magento/composer-root-update-plugin; version 1.1.2 is already in /home/jeroenvm/magento2/var.
```

**Comment by jeroenvermeulen** [comment]
Workaround:
```
ln -sf  ../../composer.json  var/composer_home/composer.json
```

**Comment by cmuench** [comment]
Maybe I found a solution.

**Comment by cmuench** [comment]
@jeroenvermeulen I added a portential fix. In my case it fixed the issue.
You can update your phar with `n98-magerun2.phar self-update --unstable` to test if it works.

**Comment by cmuench** [comment]
@jeroenvermeulen If it works, then I will create a stable release 4.7.0 very soon.

**Comment by jeroenvermeulen** [comment]
@cmuench Now I am bumping on another problem:
```
~/magento2$ n98-magerun2  -V
n98-magerun2 4.7.0-dev by netz98 GmbH

~/magento2$ n98-magerun2  sampledata:deploy

Fatal error: Class Composer\Semver\Constraint\EmptyConstraint contains 3 abstract methods and must therefore be declared abstract or implement the remaining methods (Composer\Semver\Constraint\ConstraintInterface::compile, Composer\Semver\Constraint\ConstraintInterface::getUpperBound, Composer\Semver\Constraint\ConstraintInterface::getLowerBound) in /home/jeroenvm/magento2/vendor/composer/semver/src/Constraint/EmptyConstraint.php on line 17
```

**Comment by cmuench** [comment]
@jeroenvermeulen ok. Next try. I tested only with the `setup:db-data:upgrade` command where I had the same issue.
The sampledata:deploy uses a second Composer dependency. I created a new phar file.
In my local installation the `sampledata:deploy` command is now working.

**Comment by jeroenvermeulen** [comment]
![Fixing parrot](https://cultofthepartyparrot.com/parrots/fixparrot.gif) It works!

**Comment by cmuench** [comment]
@jeroenvermeulen We have to postpone the 4.7.0 release. The changes break the self-update command.

**Comment by cmuench** [comment]
@jeroenvermeulen It's released.
