### ISSUE TITLE
Call to a member function fetchColumn() on bool in AddDefaultAuthorizationRoles

### ISSUE THREAD

**Issue by amenk** [netz98/n98-magerun2#828]
When importing the database, an error occures.
It's related to the new feature to create auth roles after the import.

The dump was created using

     n98-magerun2 db:dump --git-friendly --strip "@development @idx elasticsuite_tracker_log_* *cache*" sql/master.sql

## Expected behaviour

No error :) + Roles created

## Steps to reproduce the issue

	$ n98-magerun2 db:import --drop sql/master.sql  

		                 
	  Import MySQL Database  
		                 

	Dropped database db
	Created database db
	Importing SQL dump sql/master.sql to database db
	 905MiB 0:03:31 [4.29MiB/s] [=================================================================================================================================================>] 100%            
	Finished==========================>                ] 93% ETA 0:00:13
	PHP Fatal error:  Uncaught Error: Call to a member function fetchColumn() on bool in phar:///usr/local/bin/n98-magerun2/src/N98/Magento/Command/Database/AddDefaultAuthorizationRoles.php:40
	Stack trace:
	#0 /var/www/vendor/symfony/console/Command/Command.php(255): N98\Magento\Command\Database\AddDefaultAuthorizationRoles->execute(Object(Symfony\Component\Console\Input\StringInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
	#1 phar:///usr/local/bin/n98-magerun2/src/N98/Magento/Command/AbstractMagentoCommand.php(363): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\StringInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
	#2 phar:///usr/local/bin/n98-magerun2/vendor/symfony/console/Application.php(1027): N98\Magento\Command\AbstractMagentoCommand->run(Object(Symfony\Component\Console\Input\StringInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
	#3 phar:///usr/local/bin/n98-magerun2/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Ap in phar:///usr/local/bin/n98-magerun2/src/N98/Magento/Command/Database/AddDefaultAuthorizationRoles.php on line 40

	Fatal error: Uncaught Error: Call to a member function fetchColumn() on bool in phar:///usr/local/bin/n98-magerun2/src/N98/Magento/Command/Database/AddDefaultAuthorizationRoles.php:40
	Stack trace:
	#0 /var/www/vendor/symfony/console/Command/Command.php(255): N98\Magento\Command\Database\AddDefaultAuthorizationRoles->execute(Object(Symfony\Component\Console\Input\StringInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
	#1 phar:///usr/local/bin/n98-magerun2/src/N98/Magento/Command/AbstractMagentoCommand.php(363): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\StringInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
	#2 phar:///usr/local/bin/n98-magerun2/vendor/symfony/console/Application.php(1027): N98\Magento\Command\AbstractMagentoCommand->run(Object(Symfony\Component\Console\Input\StringInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
	#3 phar:///usr/local/bin/n98-magerun2/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Ap in phar:///usr/local/bin/n98-magerun2/src/N98/Magento/Command/Database/AddDefaultAuthorizationRoles.php on line 40

## Technical details

- Docker Container based on Debian
- n98-magerun2 db:console does work
- Magento 2.4.2 community
- Magerun Version 4.7.0 or current unstable version

## Workaround

Possible workaround would be

    n98-magerun2 db:import --skip-authorization-entry-creation --drop sql/master.sql  

But this is not yet released in 4.7.0 (this commit https://github.com/netz98/n98-magerun2/commit/4c7e49990f206bdf1bff571924c965badae06366#diff-8146d93079039b1480a297aefa5ed891a78d0e4140fdabd78881b86e5e23c2db)

**Comment by amenk** [comment]
Calling `n98-magerun2 db:add-default-authorization-entries` stand-alone after `db:import` seems to work for some reason

**Comment by amenk** [comment]
Trying with         

   $connection->setAttribute(\PDO::ATTR_ERRMODE, \PDO::ERRMODE_EXCEPTION);

I think it would generally make sense to call that in \N98\Util\Console\Helper\DatabaseHelper::getConnection

**Comment by amenk** [comment]
I found a solution, the connection has to be recreated, because of the drop, I will make a PR
