### ISSUE TITLE
sys:info command triggers composer garbage collector with possible PHP fatal error

### ISSUE THREAD

**Issue by a-dite** [netz98/n98-magerun2#897]
## Describe the bug

We have a CI Pipeline error when calling sys:info command
Somehow composer Garbage Collector is called and there is a discrepance between symfony versions.

## Technical details

```
$ mr2 sys:info;
Fatal error: Uncaught Error: Cannot call constructor in /builds/CUSTOMPROJECT/shop/vendor/symfony/finder/Comparator/DateComparator.php:48
Stack trace:
#0 phar:///usr/local/bin/n98-magerun2.phar/vendor/symfony/finder/Finder.php(154): Symfony\Component\Finder\Comparator\DateComparator->__construct('until 2021-06-1...')
#1 /builds/CUSTOMPROJECT/shop/vendor/composer/composer/src/Composer/Cache.php(205): Symfony\Component\Finder\Finder->date('until 2021-06-1...')
#2 /builds/CUSTOMPROJECT/shop/vendor/composer/composer/src/Composer/Downloader/FileDownloader.php(69): Composer\Cache->gc(15552000, 314572800)
#3 /builds/CUSTOMPROJECT/shop/vendor/composer/composer/src/Composer/Downloader/GzipDownloader.php(36): Composer\Downloader\FileDownloader->__construct(Object(Composer\IO\BufferIO), Object(Composer\Config), Object(Composer\EventDispatcher\EventDispatcher), Object(Composer\Cache), Object(Composer\Util\RemoteFilesystem))
#4 /builds/CUSTOMPROJECT/shop/vendor/composer/composer/src/Composer/Factory.php(490): Composer\Downloader\GzipDownloader->__construct(Object(Composer\IO\BufferIO in /builds/CUSTOMPROJECT/shop/vendor/symfony/finder/Comparator/DateComparator.php on line 48
```

**Comment by cmuench** [comment]
The issue is related to the Composer Garbage Collection whicn is implicit triggered ~ every 50 command call.
ForComposer 2 we can set the `COMPOSER_TEST_SUITE` environment variable during runtime to simulate a phpunit run which let Composer disables the garbage collection.
For Composer 1 this variable is not evaluated. So we have only the option to change a private static variable via reflection api.
